package forge.index

import forge.workspace.Database
import forge.workspace.FileClassification
import forge.workspace.FileRecord

/**
 * Classifies project files into 13 categories for better understanding
 * of project structure beyond the basic source/test/build categories.
 */
class FileClassificationService {

    companion object {
        private val BUILD_FILES = setOf(
            "build.gradle", "build.gradle.kts", "pom.xml", "build.sbt",
            "cargo.toml", "go.mod", "package.json", "requirements.txt",
            "setup.py", "setup.cfg", "pyproject.toml", "gemfile",
            "cmakelists.txt", "makefile", "rakefile", "build.xml"
        )

        private val CONFIG_EXTENSIONS = setOf(
            "yaml", "yml", "json", "toml", "ini", "cfg", "conf",
            "properties", "env", "config"
        )

        private val DOC_EXTENSIONS = setOf("md", "rst", "adoc", "txt", "doc", "docx")

        private val SCRIPT_FILES = setOf(
            "sh", "bash", "zsh", "fish", "ps1", "bat", "cmd"
        )

        private val ASSET_EXTENSIONS = setOf(
            "png", "jpg", "jpeg", "gif", "svg", "ico", "webp",
            "ttf", "otf", "woff", "woff2", "eot",
            "mp3", "mp4", "wav", "ogg", "webm"
        )

        private val WORKFLOW_PATTERNS = listOf(
            ".github/workflows/", "jenkinsfile", ".gitlab-ci",
            ".circleci/", ".travis.yml", "azure-pipelines",
            ".buildkite/", "bitbucket-pipelines"
        )

        private val ENVIRONMENT_FILES = setOf(
            "dockerfile", "docker-compose.yml", "docker-compose.yaml",
            "vagrantfile", "procfile", ".dockerignore",
            "terraform", ".tf"
        )

        private val MIGRATION_PATTERNS = listOf(
            "migration", "migrate", "alembic", "flyway", "liquibase",
            "db/migrate", "migrations/"
        )

        private val FIXTURE_PATTERNS = listOf(
            "fixture", "factory", "__fixtures__", "testdata",
            "test_data", "mock", "stub"
        )

        private val PROTO_EXTENSIONS = setOf("proto", "thrift", "avro", "graphql", "gql")

        private val GENERATED_MARKERS = listOf(
            "generated by", "do not edit", "auto-generated",
            "this file is generated", "code generated"
        )

        private val ENTRY_POINT_PATTERNS = mapOf(
            "kotlin" to listOf(Regex("""fun\s+main\s*\(""")),
            "java" to listOf(Regex("""public\s+static\s+void\s+main\s*\(""")),
            "python" to listOf(Regex("""if\s+__name__\s*==\s*['"]__main__['"]""")),
            "go" to listOf(Regex("""func\s+main\s*\(\s*\)""")),
            "typescript" to listOf(Regex("""app\.(listen|start)\s*\(""")),
            "javascript" to listOf(Regex("""app\.(listen|start)\s*\("""))
        )

        private val FRAMEWORK_INDICATORS = mapOf(
            "spring" to listOf("@SpringBootApplication", "@RestController", "@Service"),
            "react" to listOf("import React", "from 'react'", "from \"react\""),
            "django" to listOf("from django", "INSTALLED_APPS"),
            "flask" to listOf("from flask", "Flask(__name__)"),
            "express" to listOf("require('express')", "from 'express'"),
            "ktor" to listOf("embeddedServer", "io.ktor"),
            "fastapi" to listOf("from fastapi", "FastAPI()"),
            "rails" to listOf("Rails.application", "class ApplicationController"),
            "angular" to listOf("@Component", "@NgModule", "from '@angular"),
            "vue" to listOf("createApp", "from 'vue'"),
            "nextjs" to listOf("from 'next", "getServerSideProps", "getStaticProps")
        )
    }

    data class ClassificationResult(
        val primaryClass: String,
        val secondaryClass: String? = null,
        val frameworkHint: String? = null,
        val entryPoint: Boolean = false,
        val generated: Boolean = false
    )

    /**
     * Classify a single file.
     */
    fun classify(
        relativePath: String,
        language: String?,
        firstLines: String? = null
    ): ClassificationResult {
        val fileName = relativePath.substringAfterLast('/').lowercase()
        val ext = fileName.substringAfterLast('.', "").lowercase()
        val pathLower = relativePath.lowercase()

        // Check generated
        val isGenerated = firstLines?.lowercase()?.let { content ->
            GENERATED_MARKERS.any { marker -> content.contains(marker) }
        } ?: false
        if (isGenerated) return ClassificationResult("generated", generated = true)

        // Check workflows
        if (WORKFLOW_PATTERNS.any { pathLower.contains(it) }) {
            return ClassificationResult("workflow")
        }

        // Check environment
        if (ENVIRONMENT_FILES.any { fileName.contains(it) || pathLower.contains(it) }) {
            return ClassificationResult("environment")
        }

        // Check proto/schema
        if (ext in PROTO_EXTENSIONS) {
            return ClassificationResult("proto")
        }

        // Check migrations
        if (MIGRATION_PATTERNS.any { pathLower.contains(it) }) {
            return ClassificationResult("migration")
        }

        // Check fixtures
        if (FIXTURE_PATTERNS.any { pathLower.contains(it) }) {
            return ClassificationResult("fixture")
        }

        // Check build files
        if (fileName in BUILD_FILES || ext == "gradle" || ext == "cmake") {
            return ClassificationResult("build")
        }

        // Check config
        if (ext in CONFIG_EXTENSIONS || fileName.startsWith(".") && ext in setOf("rc", "")) {
            return ClassificationResult("config")
        }

        // Check docs
        if (ext in DOC_EXTENSIONS || pathLower.contains("doc/") || pathLower.contains("docs/")) {
            return ClassificationResult("docs")
        }

        // Check scripts
        if (ext in SCRIPT_FILES || fileName == "makefile" || fileName == "rakefile") {
            return ClassificationResult("script")
        }

        // Check assets
        if (ext in ASSET_EXTENSIONS) {
            return ClassificationResult("asset")
        }

        // Check test
        if (pathLower.contains("test") || pathLower.contains("spec") ||
            fileName.contains("test") || fileName.contains("spec")) {
            // Detect framework from content
            val framework = firstLines?.let { detectFramework(it) }
            return ClassificationResult("test", frameworkHint = framework)
        }

        // Check entry point
        val isEntryPoint = firstLines?.let { content ->
            val lang = language ?: return@let false
            ENTRY_POINT_PATTERNS[lang]?.any { pattern -> pattern.containsMatchIn(content) } ?: false
        } ?: false

        // Detect framework
        val framework = firstLines?.let { detectFramework(it) }

        // Default: source
        return ClassificationResult(
            primaryClass = "source",
            frameworkHint = framework,
            entryPoint = isEntryPoint
        )
    }

    private fun detectFramework(content: String): String? {
        for ((framework, indicators) in FRAMEWORK_INDICATORS) {
            if (indicators.any { content.contains(it) }) {
                return framework
            }
        }
        return null
    }

    /**
     * Classify all files and persist to database.
     */
    fun classifyAll(db: Database, repoPath: java.nio.file.Path): Map<String, Int> {
        val files = db.getAllFiles()
        val batch = mutableListOf<FileClassification>()
        val stats = mutableMapOf<String, Int>()

        for (file in files) {
            val filePath = repoPath.resolve(file.relativePath)
            val firstLines = try {
                if (java.nio.file.Files.exists(filePath) && (file.sizeBytes ?: 0) < 1_000_000) {
                    java.nio.file.Files.readString(filePath).take(2000)
                } else null
            } catch (_: Exception) { null }

            val result = classify(file.relativePath, file.language, firstLines)

            batch.add(FileClassification(
                id = 0,
                fileId = file.id,
                primaryClass = result.primaryClass,
                secondaryClass = result.secondaryClass,
                frameworkHint = result.frameworkHint,
                entryPoint = result.entryPoint,
                generated = result.generated
            ))

            stats[result.primaryClass] = (stats[result.primaryClass] ?: 0) + 1

            if (batch.size >= 500) {
                db.insertFileClassificationsBatch(batch)
                batch.clear()
            }
        }

        if (batch.isNotEmpty()) {
            db.insertFileClassificationsBatch(batch)
        }

        return stats
    }
}
